version: "3"

services:
  mongo:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  app:
    ports:
      - 3000:3000
    depends_on: 
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - 8081:8081
    depends_on:
      - mongo


volumes:
  dbdata6: